import Cascader from 'element-ui/lib/cascader';
import CascaderPanel from 'element-ui/lib/cascader-panel';
import Checkbox from 'element-ui/lib/checkbox';
import CheckboxGroup from 'element-ui/lib/checkbox-group';
import CheckboxButton from 'element-ui/lib/checkbox-button';
import ColorPicker from 'element-ui/lib/color-picker';
import DatePicker from 'element-ui/lib/date-picker';
import Form from 'element-ui/lib/form';
import FormItem from 'element-ui/lib/form-item';
import Input from 'element-ui/lib/input';
import Autocomplete from 'element-ui/lib/autocomplete';
import InputNumber from 'element-ui/lib/input-number';
import Pagination from 'element-ui/lib/pagination';
import Radio from 'element-ui/lib/radio';
import RadioGroup from 'element-ui/lib/radio-group';
import RadioButton from 'element-ui/lib/radio-button';
import Rate from 'element-ui/lib/rate';
import Select from 'element-ui/lib/select';
import OptionGroup from 'element-ui/lib/option-group';
import Option from 'element-ui/lib/option';
import Switch from 'element-ui/lib/switch';
import Slider from 'element-ui/lib/slider';
import Table from 'element-ui/lib/table';
import TableColumn from 'element-ui/lib/table-column';
import TimePicker from 'element-ui/lib/time-picker';
import Transfer from 'element-ui/lib/transfer';
import Tree from 'element-ui/lib/tree';
import Upload from 'element-ui/lib/upload';

export { ElRouterView } from './el-router-view';
export { ElFlex } from './el-flex';
export { ElAbsoluteLayout } from './el-absolute-layout';
export { ElIframe } from './el-iframe';
export { ElIcon } from './el-icon';
export { ElText } from './el-text';
export { ElButton, ElButtonGroup } from './el-button';
export const ElTable = Table;
export const ElTableColumn = TableColumn;
export { ElResult } from './el-result';
export { ElRow, ElCol } from './el-row';
export {
  ElContainer, ElHeader, ElAside, ElFooter, ElMain,
} from './el-container';
export { ElLink } from './el-link';
export const ElRadio = Radio;
export const ElRadioGroup = RadioGroup;
export const ElRadioButton = RadioButton;

export const ElCheckbox = Checkbox;
export const ElCheckboxGroup = CheckboxGroup;
export const ElCheckboxButton = CheckboxButton;

export const ElInput = Input;
export const ElAutocomplete = Autocomplete;
export const ElInputNumber = InputNumber;
export const ElSelect = Select;
export const ElOptionGroup = OptionGroup;
export const ElOption = Option;

export const ElCascader = Cascader;
export const ElCascaderPanel = CascaderPanel;

export const ElSwitch = Switch;
export const ElSlider = Slider;
export const ElTimePicker = TimePicker;
export const ElDatePicker = DatePicker;
export const ElUpload = Upload;
export const ElRate = Rate;
export const ElColorPicker = ColorPicker;
export const ElTransfer = Transfer;
export const ElForm = Form;
export const ElFormItem = FormItem;
export { ElTag } from './el-tag';
export { ElProgress } from './el-progress';
export const ElTree = Tree;
export const ElPagination = Pagination;
export { ElBadge } from './el-badge';
export { ElAvatar } from './el-avatar';
export { ElSkeleton, ElSkeletonItem } from './el-skeleton';
export { ElEmpty } from './el-empty';
export { ElDescriptions, ElDescriptionsItem } from './el-descriptions';
export { ElStatistic } from './el-statistic';
export { ElAlert } from './el-alert';
export {
  ElMenu, ElSubmenu, ElMenuItem, ElMenuItemGroup,
} from './el-menu';
export { ElTabs, ElTabPane } from './el-tabs';
export { ElBreadcrumb, ElBreadcrumbItem } from './el-breadcrumb';
export { ElPageHeader } from './el-page-header';
export { ElDropdown, ElDropdownMenu, ElDropdownItem } from './el-dropdown';
export { ElSteps, ElStep } from './el-steps';
export { ElDialog } from './el-dialog';
export { ElTooltip } from './el-tooltip';
export { ElPopover } from './el-popover';
export { ElPopconfirm } from './el-popconfirm';
export { ElCard } from './el-card';
export { ElCarousel, ElCarouselItem } from './el-carousel';
export { ElCollapse, ElCollapseItem } from './el-collapse';
export { ElTimeline, ElTimelineItem } from './el-timeline';
export { ElDivider } from './el-divider';
export { ElCalendar } from './el-calendar';
export { ElImage } from './el-image';
export { ElDrawer } from './el-drawer';
export { ElMessage, ElMessageDesigner } from './el-message';
export { ElNotification, ElNotificationDesigner } from './el-notification';
export { ElMessageBox, ElMessageBoxDesigner } from './el-message-box';
export { ElBacktop, ElBacktopDesigner } from './el-backtop';
